# Generated by Django 6.0.5 on 2026-05-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
